### ISSUE TITLE
'An illegal reflective access' error 

### ISSUE THREAD

**Issue by ggilfoyl** [drewkenjo/j2root#1]
When I use the j2root libraries on my laptop my code works fine, but when I try to run the same code on the jlab ifarm I get the following error message.

$COATJAVA/bin/run-groovy nde.groovy sim 45na_in inbCor firstRun.root

*****************************************
*    Running COAT-JAVA Groovy Scripts   *
*    Version : 3a  Release : 2016       *
*****************************************

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/u/apps/groovy/lib/groovy-2.4.9.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Loading EC Geometry
[DB] --->  open connection with : mysql://clas12reader@clasdb-farm.jlab.org/clas12
[DB] --->  database variation   : rga_fall2018
[DB] --->  database run number  : 11
[DB] --->  database time stamp  : Wed Dec 08 19:22:03 EST 2021
[DB] --->  database connection  : success
[DB LOAD] ---> loading data table : /geometry/pcal/pcal

[DB] --->  database disconnect  : success
SysError in <TFile::TFile>: file /run/media/gilfoyle/gpgFD/nde/lbCode-21-dec-02/rootfile/firstRun.root can not be opened (No such file or directory)

I have tried making the two environments the same, but that has not yet worked. Any thoughts would be greatly appreciated.

thanks-in-advance,

jerry gilfoyle

**Comment by drewkenjo** [comment]
I think the path where you create root file doesn't exist on ifarm: /run/media/gilfoyle/gpgFD/nde/
You should specify another path on ifarm.

**Comment by ggilfoyl** [comment]
Thanks.

________________________________________
From: Andrey ***@***.***>
Sent: Monday, December 13, 2021 5:15 PM
To: drewkenjo/j2root
Cc: Jerry Gilfoyle; Author
Subject: [EXTERNAL] Re: [drewkenjo/j2root] 'An illegal reflective access' error  (Issue #1)

External Email: Use caution in opening links, attachments, and buying gift cards.


I think the path where you create root file doesn't exist on ifarm: /run/media/gilfoyle/gpgFD/nde/
You should specify another path on ifarm.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_drewkenjo_j2root_issues_1-23issuecomment-2D992959611&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=f3LAQJhf6plqy5IpHeKnTVrJNKtFD3Y0ufHZEg0bf5k&m=qTiyHQXr5dU0ha5mATm4EQRLwjXhaZdlJ4-JSL66A2EIohI56Zi0NfEh-_PWo8fa&s=dTY2ZL7gUqo0jYN_H_Pa5-v6cT_KDYpKwoTUpOMswlw&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AB4CHGCU2R7JYAC4HEW4KCTUQZWBJANCNFSM5J7A56CA&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=f3LAQJhf6plqy5IpHeKnTVrJNKtFD3Y0ufHZEg0bf5k&m=qTiyHQXr5dU0ha5mATm4EQRLwjXhaZdlJ4-JSL66A2EIohI56Zi0NfEh-_PWo8fa&s=OMv-xeXstvp4LNN619YBdxgf06quqZhRr6TM9Sho2EA&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=f3LAQJhf6plqy5IpHeKnTVrJNKtFD3Y0ufHZEg0bf5k&m=qTiyHQXr5dU0ha5mATm4EQRLwjXhaZdlJ4-JSL66A2EIohI56Zi0NfEh-_PWo8fa&s=4XuJ8LtTXvw7AsxDFyMCJXmM4H_Xr4iLA4DyTWtf8_c&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=f3LAQJhf6plqy5IpHeKnTVrJNKtFD3Y0ufHZEg0bf5k&m=qTiyHQXr5dU0ha5mATm4EQRLwjXhaZdlJ4-JSL66A2EIohI56Zi0NfEh-_PWo8fa&s=2Xpfa4guZu1zqTo6Mxbir9xmlHCJ6SogFdhioEVy4-o&e=>.
